name: mkdir example

on:
  push:
    branches: master
  
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create dir
        run: |
          mkdir mydirname
        
